version: '4.0'

actions:
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz

  generate_report:
    run: r:v2 analysis/report.R
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        chart: output/report.png
  generate_status:
    run: r:v2 analysis/status.R
    needs: [generate_dataset]
    outputs:
      moderately_sensitive:
        chart: output/status.csv    
  generate_demographics:
    run: r:v2 analysis/demographics.R
    needs: [generate_status]
    outputs:
      moderately_sensitive:
        plot1: output/sex_distribution.png
        plot2: output/vaccination_status_distribution.png
        plot3: output/age_distribution.png
        plot4: output/age_by_vaccination.png
        plot5: output/vaccination_dates_distribution.png
        plot6: output/sex_vs_vaccination.png
        plot7: output/age_group_vs_vaccination.png
  test_ml_model:
    run: r:v2 analysis/ml.R
    needs: [generate_status]
    outputs:
      moderately_sensitive:
        plot: output/predicted_prob_plot.png

  generate_viz:
    run: r:v2 analysis/visualisasi.R
    needs: [generate_status]
    outputs:
      moderately_sensitive:
        plot: output/1_survival_by_age.png
        plot1: output/2_alluvial_flow.png
        plot2: output/3_patient_heatmap.png
        plot3: output/4_age_distribution.png
        plot4: output/5_mosaic_plot.png
        plot5: output/6_forest_plot.png
        plot6: output/7_multifactor_bars.png
        plot7: output/8_predicted_probability.png
        plot8: output/9_waffle_chart.png
        plot9: output/10_dashboard.png

  generate_viz2:
    run: r:v2 analysis/viz2.R
    needs: [generate_status]
    outputs:
      moderately_sensitive:
        plot: output/11_new_dashboard.png
        plot1: output/12_dashboard_age.png
        plot2: output/13_mortality_heatmap.png
        plot3: output/14_patient_flow.png
        plot4: output/15_risk_stratification.png
        plot5: output/16_age_violin_plot.png
        plot6: output/17_mortality_by_sex_age.png
        plot7: output/18_correlation_matrix.png
        plot8: output/19_survival_curve.png
        plot9: output/20_summary_statistics.png


